const questionsMock = [
  {
    id: 1,
    question: "Qual é a capital da França?",
    options: ["Madrid", "Londres", "Paris", "Berlim", "Roma"],
    correctAnswer: "Paris",
  },
  {
    id: 2,
    question: "Quem escreveu 'Dom Quixote'?",
    options: [
      "Machado de Assis",
      "Miguel de Cervantes",
      "William Shakespeare",
      "José de Alencar",
      "Eça de Queirós",
    ],
    correctAnswer: "Miguel de Cervantes",
  },
  {
    id: 3,
    question: "Qual é o maior planeta do Sistema Solar?",
    options: ["Terra", "Marte", "Júpiter", "Vênus", "Saturno"],
    correctAnswer: "Júpiter",
  },
  {
    id: 4,
    question: "Quem pintou a Mona Lisa?",
    options: [
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Pablo Picasso",
      "Michelangelo",
      "Claude Monet",
    ],
    correctAnswer: "Leonardo da Vinci",
  },
  {
    id: 5,
    question: "Qual é o símbolo químico do ouro?",
    options: ["Au", "Ag", "O", "Fe", "Hg"],
    correctAnswer: "Au",
  },
  {
    id: 6,
    question: "Quem foi o primeiro homem a pisar na Lua?",
    options: [
      "Buzz Aldrin",
      "Yuri Gagarin",
      "Neil Armstrong",
      "Michael Collins",
      "Alan Shepard",
    ],
    correctAnswer: "Neil Armstrong",
  },
  {
    id: 7,
    question: "Quantos lados tem um hexágono?",
    options: ["4", "5", "6", "7", "8"],
    correctAnswer: "6",
  },
  {
    id: 8,
    question: "Qual é o maior oceano do mundo?",
    options: [
      "Oceano Atlântico",
      "Oceano Índico",
      "Oceano Ártico",
      "Oceano Antártico",
      "Oceano Pacífico",
    ],
    correctAnswer: "Oceano Pacífico",
  },
  {
    id: 9,
    question: "Quem foi o autor de 'O Pequeno Príncipe'?",
    options: [
      "J.K. Rowling",
      "Antoine de Saint-Exupéry",
      "George Orwell",
      "Mark Twain",
      "Charles Dickens",
    ],
    correctAnswer: "Antoine de Saint-Exupéry",
  },
  {
    id: 10,
    question: "Quantos ossos tem o corpo humano adulto?",
    options: ["200", "206", "212", "220", "198"],
    correctAnswer: "206",
  },
  {
    id: 11,
    question: "Quem descobriu o Brasil?",
    options: [
      "Pedro Álvares Cabral",
      "Cristóvão Colombo",
      "Vasco da Gama",
      "Fernando de Magalhães",
      "Americo Vespúcio",
    ],
    correctAnswer: "Pedro Álvares Cabral",
  },
  {
    id: 12,
    question: "Qual é a moeda oficial do Japão?",
    options: ["Yuan", "Dólar", "Euro", "Iene", "Rupia"],
    correctAnswer: "Iene",
  },
  {
    id: 13,
    question: "Qual é o gás mais abundante na atmosfera terrestre?",
    options: ["Oxigênio", "Dióxido de Carbono", "Hidrogênio", "Nitrogênio", "Hélio"],
    correctAnswer: "Nitrogênio",
  },
  {
    id: 14,
    question: "Quem inventou a lâmpada elétrica?",
    options: [
      "Nikola Tesla",
      "Benjamin Franklin",
      "Thomas Edison",
      "Alexander Graham Bell",
      "James Watt",
    ],
    correctAnswer: "Thomas Edison",
  },
  {
    id: 15,
    question: "Qual é o país mais populoso do mundo?",
    options: ["Índia", "Estados Unidos", "Brasil", "China", "Indonésia"],
    correctAnswer: "China",
  },
];

export default questionsMock;
